<script src="<?= assets_url('lib/jquery/jquery.min.js'); ?>"></script>
<script src="<?= assets_url('lib/bootstrap/js/bootstrap.bundle.min.js'); ?>"></script>
<script src="<?= assets_url('lib/easing/easing.min.js'); ?>"></script>
<script src="<?= assets_url('lib/superfish/hoverIntent.js'); ?>"></script>
<script src="<?= assets_url('lib/superfish/superfish.min.js'); ?>"></script>
<script src="<?= assets_url('lib/wow/wow.min.js'); ?>"></script>
<script src="<?= assets_url('lib/owlcarousel/owl.carousel.min.js'); ?>"></script>
<script src="<?= assets_url('lib/magnific-popup/magnific-popup.min.js'); ?>"></script>
<script src="<?= assets_url('lib/sticky/sticky.js'); ?>"></script>
<script src="<?= assets_url('contactform/contactform.js'); ?>"></script>
<script src="<?= assets_url('js/main.js'); ?>"></script>